spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${MYSQL_PROJECT_URL}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: update # 기존 스키마를 유지하고 필요한 경우에만 업데이트
        show-sql: true # SQL 쿼리 출력
        properties:
          hibernate:
            format_sql: true # SQL 쿼리 포맷팅
      database-platform: hibernate.dialect.MySQL8Dialect # MySQL 8이상 버전 사용 명시

---
spring:
  config:
    activate:
      on-profile: prod
  datasource: #DatasourceConfig에서 설정
#    url: ${PROD_MYSQL_PROJECT_URL}?serverTimezone=UTC&characterEncoding=UTF-8
#    username: ${PROD_MYSQL_USERNAME}
#    password: ${PROD_MYSQL_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: update # 기존 스키마를 유지하고 필요한 경우에만 업데이트
        show-sql: true # SQL 쿼리 출력
        properties:
          hibernate:
            format_sql: true # SQL 쿼리 포맷팅
      database-platform: hibernate.dialect.MySQL8Dialect # MySQL 8이상 버전 사용 명시
