spring:
  application:
    name: project-api

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: mybatis/mappers/*.xml

logging:
  config: classpath:config/logback-spring.xml

secret:
  key:
    path: classpath:secret.key